### ISSUE TITLE
Medium icon too small?

### ISSUE THREAD

**Issue by fefo-dev** [optix2000/totsugeki#26]
![image](https://images2.imgbox.com/c9/55/1VdSchWl_o.png)

Stupid but annoying peeve - the May icon looks bad on desktop (medium size view) and on Start menu. Probably fixable by changing icon_48.png to 🐬 too (if you agree).

**Comment by optix2000** [comment]
Unfortunately, [windows icons are a shitshow](https://stackoverflow.com/questions/3236115/which-icon-sizes-should-my-windows-applications-icon-include).

The [48px icon](https://github.com/optix2000/totsugeki/blob/master/winres/icon_48.png) actually has proper resizing so it shouldn't look that bad, but it looks like Windows is (badly) resizing down the 256px icon.

I believe this was fixed in v1.1.1, since prior to that, totsugeki only had the 256px icon. If you've already upgraded, then windows might have cached the icon. Try renaming totsugeki and see if that still happens.
![image](https://user-images.githubusercontent.com/1121068/128646328-4ae1e846-2ae3-44cd-8915-69cd51cbb3b0.png)

**Comment by fefo-dev** [comment]
The icon change on 1.0 (this is 1.1.1) was what prompted this "issue" initially. Took several cache clears for me to figure that maybe there's more than one icon available between zoom levels.

A clearer example perhaps (1080p, 100% scaling):

![image](https://images2.imgbox.com/d9/82/dU7zQLZW_o.png)
- Left: Windows small default on desktop;
- Center: One zoom step beyond that;
- Right: Windows medium default.

Again not a bug, just a taste difference as I much prefer the dolphin emoji for medium instead of a far more detailed icon in such a small resolution.

Thanks for the attention, fell free to close if you're good with your choice.

**Comment by fefo-dev** [comment]
> Unfortunately, Windows icons are a shitshow.

Forgot to read your note and welp, I'll trust your judgement 😁

**Comment by optix2000** [comment]
I see your point now, I'll have to sit on this for a bit.

I didn't really notice in testing since all my screens were 125% or 150% scaling.

**Comment by fefo-dev** [comment]
I was reminded of Windows scaling mid-typing, which says a lot about this.

Much appreciated.

**Comment by optix2000** [comment]
Slept on this and my love for [4]6S wins out, so I won't be changing it.

I do agree with the accessibility issue and appreciate the report.

In your case, you can change the icon of the shortcut to something else as a workaround.
