### ISSUE TITLE
Allow building/installing on Linux

### ISSUE THREAD

**Issue by tommyalatalo** [optix2000/totsugeki#74]
I'd love to try the mod on Linux with Proton to see how it works, but I can't seem to build/install this, as there is some hard dependency on something for Windows?

```
❯ go install github.com/optix2000/totsugeki
package github.com/optix2000/totsugeki
        imports golang.org/x/sys/windows: build constraints exclude all Go files in /home/tommy/go/pkg/mod/golang.org/x/sys@v0.0.0-20210925032602-92d5a993a665/windows
```

**Comment by notKamui** [comment]
it uses strict syscalls to windows so you would either need to make a layer, or completely redo the script for linux

**Comment by gadanidis** [comment]
You can run it with Proton using this script by FrozenFish24 (discussed in #10): https://gist.github.com/FrozenFish24/32373f530dfdb1b2cbb54309a4fa9aaa 

You then set your launch options to `"/path/to/totsugeki.sh" %command%`

I have been using it and it works well. It might be worthwile to put this in the readme or something so that this question doesn't keep coming up.

**Comment by optix2000** [comment]
Simply not happening because totsugeki built using windows syscalls (as @notKamui mentioned).

The syscalls aren't complex so Wine and Proton should be able to run totsugeki without any issues.

Will pin this issue so other Linux users can use the same method.
